services:
  pandora-bot:
    build: .
    container_name: pandora-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./user_stats.json:/app/user_stats.json

volumes: {}
